### ISSUE TITLE
function opt.candidate line 26

### ISSUE THREAD

**Issue by singlecoated** [bioliyezhang/ISnorm#1]
Hi,

I'm currently doing some tests with your package and looking at the code of the opt.candidate function, line 26, I see

    baseset<-max((1:length(candidate_res$spike))[instability<0.1])

Should the 0.1 at the end be the baseline_threshold variable instead or is this value chosen and hard-coded as the empirical choice you mention in your paper ?

Many thanks in advanced.

**Comment by bioliyezhang** [comment]
Hi,

0.1 is the baseline_threshold variable and it is equal to 
`baseset<-max((1:length(candidate_res$spike))[instability<baseline_threshold])`. 
What we set baseline_threshold to be 0.1 is an empirical choice based on many tested data. According to your analysis, you can change the baseline_threshold value.

Best wishes,

**Comment by singlecoated** [comment]
Hi,

many thanks for your fast answer, it is now clear, and of course thanks also for sharing your package with the community. We are currently working with a large SC dataset and evaluating several normalization methods, and we found ISnorm to be very interesting for that purpose.

Warm regards.
